### ISSUE TITLE
implement custom back button

### ISSUE THREAD

**Issue by eliprodigy** [goblinbr/manager-react-native-app#3]
Hi, thank you for this simple example 
I'm trying to add back action but it doesnt seem to work
can you tell why?

In **navigateTo.js** file i added

export const goBack = (dispatch, resetStack) => {
   dispatch(NavigationActions.back({
      key: null
    }));
};
 
Thanks

**Comment by goblinbr** [comment]
Hi @eliprodigy 

Just pushed a commit on another branch with a custom back button

Feel free to ask if you have any question about it.
